### ISSUE TITLE
Issues with running example data sets

### ISSUE THREAD

**Issue by sebricgithub** [LewisLabUCSD/GlyCompareCT#3]
Hi,
I am attempting to get GlyCompareCT up and running, however, I run into issues in analyzing the example data sets. Here is my most recent error:

` ` `
(glycompareCT) C:\Users\seaba\GlyCompareCT\Examples>python ../glyCompareCT.py structure -a test1_abd.csv -v test1_var.csv -o test1/ -p glycoCT -b -m integer -c 2
Validating input files...
Traceback (most recent call last):
  File "C:\Users\seaba\GlyCompareCT\glyCompareCT.py", line 685, in <module>
    main()
  File "C:\Users\seaba\GlyCompareCT\glyCompareCT.py", line 54, in main
    input_validation(args)
  File "C:\Users\seaba\GlyCompareCT\glyCompareCT.py", line 103, in input_validation
    assert os.path.isdir(os.sep.join(args.output_directory.split(os.sep)[:-1])), "Invalid output path, check the path: " + os.sep.join(args.output_directory.split(os.sep)[:-1])
AssertionError: Invalid output path, check the path:
` ` `
Note a directory to test1 has been created but this error is still returned. 
My current directory is 

` ` `
(glycompareCT) C:\Users\seaba\GlyCompareCT\Examples>dir
 Volume in drive C is Windows
 Volume Serial Number is A414-7917

 Directory of C:\Users\seaba\GlyCompareCT\Examples

2024-05-03  17:28    <DIR>          .
2024-05-03  17:29    <DIR>          ..
2024-05-03  17:14             8 196 .DS_Store
2024-05-03  17:14    <DIR>          Jin2017
2024-05-03  17:28    <DIR>          test1
2024-05-03  17:14                28 test1_abd.csv
2024-05-03  17:14             2 084 test1_var.csv
2024-05-03  17:14                28 test2_abd.csv
2024-05-03  17:14             2 084 test2_var.csv
2024-05-03  17:14                42 test3_abd.csv
2024-05-03  17:14             2 084 test3_var.csv
2024-05-03  17:14                28 test4_abd.csv
2024-05-03  17:14             2 084 test4_var.csv
               9 File(s)         16 658 bytes
               4 Dir(s)  344 891 121 664 bytes free
` ` `

Current conda version is 24.4.0 and current python version is 3.10.14.final.0
platform : win-64 
Any help would be greatly appreciated, thanks.

**Comment by zyj1729** [comment]
Could you try "-o .\test1\", leave everything else the same?
